version: "3"
services:
    server:
        build: ./server
        expose:
          - 4000
        ports:
          - 4000:4000
        volumes:
          - ./server:/code
        environment:
          - FLASK_ENV=development
          - FLASK_APP=app.py
          - FLASK_DEBUG=1
    react:
        build: ./frontend
        expose:
          - 1234
        ports:
          - 1234:1234
        volumes:
          - ./frontend/src:/code/src
          - ./frontend/public:/code/public
        links:
          - "server:server"
    mongo:
        image: "mongo"
        environment:
          - MONGO_INITDB_DATABASE=minecraftapp
          - MONGO_INITDB_ROOT_USERNAME=yoda
          - MONGO_INITDB_ROOT_PASSWORD=theforce
        volumes:
          - ./init-mongo.js:/src/init-mongo.js:ro
          - ./mongo-volume:/data/db
        ports:
          - 27017:27017
